"""Type stubs for SQLAlchemy.orm."""

from typing import Any, Generic, TypeVar

T = TypeVar("T")

class Session:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def query(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, instance: Any) -> None: ...
    def add_all(self, instances: list[Any]) -> None: ...
    def delete(self, instance: Any) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def execute(self, *args: Any, **kwargs: Any) -> Any: ...
    def scalar(self, *args: Any, **kwargs: Any) -> Any: ...
    def flush(self) -> None: ...

def sessionmaker(*args: Any, **kwargs: Any) -> Any: ...
